# Generated by Django 3.1.7 on 2021-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
