# Generated by Django 3.1.7 on 2021-05-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
